databases:
- name: CSE340-PostgreSQL3
  databaseName: cse340_b6r4
  user: cse340
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "17"
version: "1"